# Generated by Django 5.2.4 on 2025-08-16 07:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jardin',
            fields=[
                ('idJar', models.CharField(help_text="Identifier d'un jardin", max_length=2, primary_key=True, serialize=False)),
                ('nomJar', models.CharField(help_text="Nom d'un description", max_length=50)),
                ('adresse', models.CharField(help_text="Adresse d'un jardin", max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('idMem', models.IntegerField(auto_created=True, help_text='Identifiant d’un membre.', primary_key=True, serialize=False)),
                ('nomMem', models.CharField(help_text='Nom et prénom d’un membre.', max_length=50)),
                ('genre', models.CharField(choices=[('0', 'Women'), ('1', 'Men')], help_text="Genre d’un membre : 'M' pour Masculin et 'F' pour Féminin.", max_length=1)),
                ('dateNais', models.DateField(help_text='Date de naissance d’un membre.')),
                ('email', models.CharField(help_text='Adresse email d’un membre.', max_length=50, unique=True)),
                ('mdp', models.CharField(help_text='Mot de passe d’un membre.', max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Parcelle',
            fields=[
                ('idPar', models.CharField(auto_created=True, help_text='Identifiant d’une parcelle d’un jardin.', primary_key=True, serialize=False)),
                ('numPar', models.IntegerField(help_text='Numéro d’une parcelle d’un jardin.')),
                ('idJar', models.ForeignKey(help_text='Identifiant d’un jardin.', on_delete=django.db.models.deletion.CASCADE, to='bd2025.jardin')),
            ],
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateDep', models.DateField(help_text='Date de début de l’affectation d’une parcelle à un membre')),
                ('idMem', models.ForeignKey(help_text='Identifiant d’un Memebr.', on_delete=django.db.models.deletion.CASCADE, to='bd2025.member')),
                ('idPar', models.ForeignKey(help_text='Identifiant d’un Parcelle.', on_delete=django.db.models.deletion.CASCADE, to='bd2025.parcelle')),
            ],
        ),
    ]
